spring.application.name=metalurgica1

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER_NAME}
spring.datasource.password=${DB_PASSWORD}


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=${DIALECT}

server.port=${PORT}

jwt.secret=${SECRET_KEY}
jwt.expiration-ms=86400000

resend.api.key=${RESEND_API_KEY:re_a7wpjjpt_EQrhWzR1tG8k8nAwKuGcCoDx}